### ISSUE TITLE
<section> as Slide remains blank

### ISSUE THREAD

**Issue by xunum** [zurb/orbit#108]
Hi,

i tried to use the orbit slider on a news archive in the cms contao. But the news output is organized in sections with the html5 tag <section>, though the slider didn't work.

After lookin' through the code i found this line

``` javascript
this.$slides=this.$element.children("img, a, div");
```

and changed it to 

``` javascript
this.$slides=this.$element.children("section, img, a, div");
```

cause i thought this would easily solve the problem. But the slider now remains blank. I don't have a chance to use divs cause this would imply high effort. Maybe you can help me, and use this as a change to the code (it would be nice to have <section> or <article> as slides, if the effort is not that high).

**Comment by xunum** [comment]
As i thought while writing i read the foundation.css a second time and found out, that you have to add

``` css
 .orbit>section {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%; 
        }
```

And voila it works ;)

Maybe this could be an update to orbit and foundation
