### ISSUE TITLE
Disable timer stops animation

### ISSUE THREAD

**Issue by digitup** [zurb/orbit#46]
When setting Timer to false. the slider doesn't animate the images and just display the first image. How can I get around that?

**Comment by mkelly12** [comment]
Right, that option is a little confusion. Setting timer to false actually disable to auto advance of slides altogether.

What you really want to do is `display: none;` the timer element if you don't want to show it.

``` css
.orbit-wrapper .timer { visibility: hidden; }
```
